name: sqlite3_simple
description: "基于 Simple (支持中文和拼音的 SQLite fts5 全文搜索扩展) 和 sqlite3.dart 的 Flutter 库，用于 SQLite 中文和拼音全文搜索。"
version: 1.0.0
homepage: https://github.com/SageMik/sqlite3_simple

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  plugin_platform_interface: ^2.0.2
  sqlite3: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sagemik.sqlite3_simple
        ffiPlugin: true
      ios:
        pluginClass: Sqlite3SimplePlugin
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
#        pluginClass: Sqlite3SimplePlugin

  assets:
    - assets/cpp_jieba_dict/