name: sqlite3_simple_core
description: "基于 Simple (支持中文和拼音的 SQLite fts5 全文搜索扩展) 和 sqlite3.dart 的 Dart 库，用于 SQLite 中文和拼音全文搜索。"
version: 3.0.0
homepage: https://github.com/SageMik
repository: https://github.com/SageMik/sqlite3_simple
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

topics:
  - sqlite
  - fts5
  - pinyin
  - chinese
  - tokenizer
  - ffi
  - hooks

dependencies:
  archive: ^4.0.0
  code_assets: ^1.0.0
  crypto: ^3.0.6
  hooks: ^1.0.0
  meta: ^1.19.0
  native_toolchain_c: ^0.17.5
  path: ^1.9.0
  sqlite3: ^3.3.0
  wasd: ^0.2.0
  web: ^1.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
